all: direktespolynom.png hornerpolynom.png taylorunterschiede.txt

taylorunterschiede.txt: taylorunterschiede.m

direktespolynom.png: polynomundhorner.m
	octave polynomundhorner.m

hornerpolynom.png: direktespolynom.png
